# Generated by Django 2.2.2 on 2019-07-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('cat_img', models.ImageField(default='', upload_to='myapp/images')),
                ('price1', models.IntegerField(default=0)),
                ('price2', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=400)),
                ('image', models.ImageField(default='', upload_to='myapp/images')),
            ],
        ),
    ]
